{{- define "lib.component.workload.allowed" -}} {{- /* define[0] */ -}}
{{ index .Chart.Annotations "allowed_workload_kinds" }}
{{- end -}} {{- /* /define[0] */ -}}

{{- define "lib.component.workload" -}} {{- /* define[0] */ -}}
{{- include "lib.err.noCtx" . -}}
{{
	$labels := include "lib.metadata.mergeLabels"
	(dict
		"ctx" .ctx
		"global" .ctx.Values.metadata.labels
		"local" .ctx.Values.base.workload.labels
	)
}}
{{- 
	$metadata := include "lib.metadata" 
	(dict 
		"ctx" .ctx 
		"annotations" .Values.base.workload.annotations
		"labels" $labels
	) 
}}
{{- if eq .Values.base.workload.kind "Deployment" -}} {{- /* if[0] */ -}}
{{- if contains .Values.base.workload.kind (include "lib.component.workload.allowed" .) }}{{- /* if[0] */ -}}
{{- 
	include "lib.core.deployment" 
	(dict "ctx" . "metadata" $metadata) 
}} 
{{- else -}}
{{- fail (printf "workload kind is not allowed: %s" .Values.base.workload.kind) -}}
{{- end }}{{- /* if[1] */ -}}
{{- end -}} {{- /* /if[0]*/ -}}
{{- end -}}{{- /* /define[0] */ -}}
