# -- Base is the base layer of the an application. Mostly it shouldn't be edited.
# -- Only one workload entry is allowed per release
# -- workload is either Deployment/DaemonSet/StatefulSet/CronJob
#metadata:
#  annotations:
#    test1: global

shortcuts:
  hostname: test.company

base:
  workload:
    replicas: 1
    # -- Deployment/DaemonSet/StatefulSet/CronJob
    kind: Deployment
    # -- Metadata to be added to a workload object
    #metadata:
    #  annotations:
    #    test: local
    strategy:
      type: RollingUpdate
    securityContext:
      seLinuxOptions:
        level: s0:c123,c456
    containers:
      vaultwarden:
        volumeMounts:
          storage:
            data: 
              path: /tmp
          files:
            main:
              path: /test
        ports:
          vaultwarden: 
            - https
            - http
        livenessProbe:
          tcpSocket:
            port: 25
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 25
          initialDelaySeconds: 3
          periodSeconds: 3
        startupProbe:
          tcpSocket:
            port: 25
          initialDelaySeconds: 3
          periodSeconds: 3
        image:
          registry: registry.hub.docker.com
          repository: stalwartlabs/mail-server
          pullPolicy: Always
        envFrom:
          main:
            remove: []
          secrets:
            remove: []
          raw:
        command:
          - sh
        args:
          - test

ingress:
  main:
    enabled: true
    class: traefik
    rules:
      - host: '{{ .Values.shortcuts.hostname }}'
        http:
          paths:
            - backend:
                service:
                  name: '{{ include "chart.fullname" $ }}-main'
                  port:
                    number: 8080
              path: /
              pathType: Prefix
    tls:
      - hosts:
          - '{{ .Values.shortcuts.hostname }}'
        secretName: '{{ .Values.shortcuts.hostname }}'

services:
  vaultwarden:
    enabled: true
    type: ClusterIP
    ports:
      https:
        port: 443
        targetPort: 443
        protocol: TCP
      http:
        port: 80
        targetPort: 80
        protocol: TCP

storage:
  data:
    enabled: true
    storageClassName: default
    size: 1Gi
    accessModes:
      - ReadWriteMany
            
config:
  env:
    main:
      enabled: true
      sensitive: false
      data:
        USERNAME: test
    secrets:
      enabled: false
      sensitive: true
      data:
        PASSWORD: test
  files:
    main:
      enabled: true
      sensitive: false
      entries: 
        file.txt:
          data: test
      
